# Generated by Django 3.1.4 on 2021-10-26 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211026_1818'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
