# Generated by Django 3.1.4 on 2021-09-17 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('users', '0004_auto_20210917_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationitem',
            name='room',
        ),
        migrations.AddField(
            model_name='reservationitem',
            name='booking',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bookings.booking'),
        ),
    ]
