# Generated by Django 3.1.4 on 2021-09-29 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210917_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationitem',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='reservationitem',
            name='reservation_list',
        ),
        migrations.DeleteModel(
            name='GuestReservationList',
        ),
        migrations.DeleteModel(
            name='ReservationItem',
        ),
    ]
