# Generated by Django 3.1.4 on 2021-12-11 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211211_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone',
            new_name='mobile',
        ),
    ]
