# Generated by Django 3.1.4 on 2021-08-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=3)),
                ('room_picture', models.ImageField(default='', upload_to='room_pictures/')),
                ('room_type', models.CharField(choices=[('SINGLE ROOM', 'Single Room'), ('DOUBLE ROOM', 'Double Room'), ('TRIPLE ROOM', 'Triple Room'), ('QUAD ROOM', 'Quad Room')], default='SINGLE ROOM', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('room_price', models.DecimalField(decimal_places=2, default='1000.00', max_digits=9)),
            ],
        ),
    ]
