# Generated by Django 3.1.4 on 2021-08-18 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('SINGLE ROOM', 'Single Room'), ('DOUBLE ROOM', 'Double Room'), ('TRIPLE ROOM', 'Triple Room'), ('QUAD ROOM', 'Quad Room')], default='SINGLE ROOM', max_length=20)),
                ('first_item', models.CharField(blank=True, max_length=20)),
                ('second_item', models.CharField(blank=True, max_length=20)),
                ('third_item', models.CharField(blank=True, max_length=20)),
                ('fourth_item', models.CharField(blank=True, max_length=20)),
                ('fifth_item', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='amenities_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.amenities'),
        ),
    ]
