version: '3'

services: 
    # rabbitmq service container
    rabbitmq:
        image: rabbitmq:3.9-management-alpine
        container_name: 'LeisuureInn_rabbitmq'
        ports: 
            - 5672:5672
            - 15672:15672

    # celery service container
    celery:
        build: .
        container_name: 'celery_LeisureInn'
        command: celery -A LeisureInn worker --loglevel=info
        # volumes: 
        #     - .:/code
        depends_on: 
            - rabbitmq
    
    # for monitoring celery operation
    flower:
        build: .
        container_name: 'celery_flower'
        command: celery -A LeisureInn flower
        # volumes:
        #     - .:/code
        ports:
            - 5555:5555
        depends_on: 
            - celery
            - rabbitmq

    # database(db) service container
    db:
        image: postgres:13.4-alpine
        container_name: "LeisureInn_db"
        environment:
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        # volumes:
        #     - ./data/db:/var/lib/postgresql/data


    # redis service container
    redis:
        image: redis:6.2
        container_name: 'LeisureInn_redis'
        command: redis-server
        ports: 
            - 6379:6379


    # web service container
    web:
        build: .
        container_name: 'LeisureInn_web'
        # command: python /code/manage.py runserver 0.0.0.0:8000
        # command: gunicorn LeisureInn.wsgi -b 0.0.0.0:8000
        command: daphne -b 0.0.0.0 -p 8000 LeisureInn.asgi:application # running the application with Daphne
        environment: 
            - DEBUG=0
            - ENVIRONMENT=production
            - SECRET_KEY=${SECRET_KEY}
            - CLOUDAMQP_URL=${CLOUDAMQP_URL}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - FLUTTERWAVE_TEST_SECRET_KEY=${FLUTTERWAVE_TEST_SECRET_KEY}
            - FLUTTERWAVE_TEST_PUBLIC_KEY=${FLUTTERWAVE_TEST_PUBLIC_KEY}
            - DROPBOX_ACCESS_TOKEN=${DROPBOX_ACCESS_TOKEN}
            - DROPBOX_CONSUMER_KEY=${DROPBOX_CONSUMER_KEY}
            - DROPBOX_CONSUMER_SECRET=${DROPBOX_CONSUMER_SECRET}
            - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
            - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
            - VAPID_ADMIN_EMAIL=${VAPID_ADMIN_EMAIL}
            - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
            - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
            - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
            - EMAIL_HOST_USER=${EMAIL_HOST_USER}
            - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
            - SENDINBLUE_API_KEY=${SENDINBLUE_API_KEY}
            - MAILJET_API_KEY=${MAILJET_API_KEY}
            - MAILJET_SECRET_KEY=${MAILJET_SECRET_KEY}
        # volumes: 
        #     - .:/code
        ports: 
            - 8000:8000
        depends_on: 
            - db
        links: 
            - rabbitmq  # so that web service knows about rabbitmq service
            - redis # so theat web service knows about redis service