# Generated by Django 3.1.4 on 2022-03-22 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='hotel_services/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='hotel_services/')),
                ('plan', models.CharField(choices=[('STANDARD', 'standard'), ('MASTER', 'master'), ('PREMIUM', 'premium')], max_length=50)),
                ('days', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(default='', max_length=50)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_services.service')),
            ],
        ),
        migrations.CreateModel(
            name='OneTimeService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_service', to='hotel_services.service')),
            ],
        ),
        migrations.CreateModel(
            name='GuestOneTimeServicePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=True)),
                ('paid_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_services.onetimeservice')),
            ],
        ),
        migrations.CreateModel(
            name='GuestCreatedSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelled', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_cancelled', models.DateTimeField(blank=True)),
                ('payment_id', models.IntegerField(default=0)),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_services.subscription')),
            ],
        ),
    ]
