# Generated by Django 3.1.4 on 2022-02-02 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscription',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='subscription',
            name='image',
            field=models.ImageField(default='', upload_to='hotel_services/'),
        ),
        migrations.CreateModel(
            name='GuestCreatedSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_cancelled', models.DateTimeField(blank=True)),
                ('payment_id', models.IntegerField(default=0)),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_services.subscription')),
            ],
        ),
    ]
