# Generated by Django 3.1.4 on 2022-01-01 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_services', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
