# Generated by Django 3.1.4 on 2022-03-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestcreatedsubscription',
            name='date_cancelled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
