# Generated by Django 3.1.4 on 2022-02-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_services', '0002_auto_20220202_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestcreatedsubscription',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
