# Generated by Django 3.1.4 on 2022-01-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_services', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
    ]
