# Generated by Django 3.1.4 on 2022-01-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_services', '0004_subscription_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='image',
            field=models.ImageField(default='', upload_to='hotel_services/'),
        ),
    ]
