# Generated by Django 3.1.4 on 2022-02-03 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_services', '0004_guestonetimeservicepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_services.service')),
            ],
        ),
    ]
