# Generated by Django 3.1.4 on 2022-01-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_services', '0005_subscription_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
