# Generated by Django 3.1.4 on 2022-02-03 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_services', '0005_onetimeservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimeservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_service', to='hotel_services.service'),
        ),
    ]
