# Generated by Django 3.1.4 on 2022-01-29 05:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel_services', '0006_subscription_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestPaidSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 1, 29, 5, 33, 38, 934827))),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_services.subscription')),
            ],
        ),
    ]
