# Generated by Django 3.1.4 on 2022-02-03 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_services', '0006_auto_20220203_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestonetimeservicepayment',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_services.onetimeservice'),
        ),
    ]
