# Generated by Django 3.1.4 on 2022-01-29 05:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_services', '0007_guestpaidsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestpaidsubscription',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 29, 5, 35, 2, 689350, tzinfo=utc)),
        ),
    ]
