# Generated by Django 3.1.4 on 2022-01-29 05:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_services', '0008_auto_20220129_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestpaidsubscription',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
