# Generated by Django 3.1.4 on 2022-01-30 15:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel_services', '0009_auto_20220129_0535'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GuestPaidSubscription',
            new_name='GuestCreatedSubscription',
        ),
    ]
