# Generated by Django 3.1.4 on 2022-01-30 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_services', '0010_auto_20220130_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestcreatedsubscription',
            name='paid',
        ),
    ]
