# Generated by Django 3.1.4 on 2021-09-03 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_firstname', models.CharField(max_length=50)),
                ('guest_lastname', models.CharField(max_length=50)),
                ('guest_email', models.EmailField(default=None, max_length=50)),
                ('guest_telephone', models.CharField(default=None, max_length=12)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='rooms.room')),
            ],
        ),
    ]
