# Generated by Django 3.1.4 on 2021-08-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_email',
            field=models.EmailField(default=None, max_length=50),
        ),
    ]
