# Generated by Django 3.1.4 on 2021-09-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
