# Generated by Django 3.1.4 on 2021-09-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_pinaxuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PinaxUser',
        ),
    ]
