# Generated by Django 3.1.4 on 2021-10-23 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest_chatRoom', '0003_auto_20211016_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
    ]
