# Generated by Django 3.1.4 on 2021-10-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_chatRoom', '0004_remove_message_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(),
        ),
    ]
